### ISSUE TITLE
Question on Install

### ISSUE THREAD

**Issue by Garzlok** [baronbrew/tilt-repeater-js#1]
First, thanks for making this available.

I have an MDBT42Q recently updated to 2v06 Espruino Firmware. I must confess, I'm new to Espruino, and I'm having difficulties making the JavaScript work on the MDBT42Q.

Through the Espruino Web IDE I can successfully Flash any of the JavaScripts in your repository (that are not for Pixl) onto the board, but I can't get it to pick up my tilt signals (either black, orange, blue, or red (all v3 Tilts)). When I press the D0 button, I get 8 green LED blinks, but when I stop on 3, 5, 6, or 8, I don't get a green blink for connection and the signal is not being repeated and making it to my phone/or iPad. Also, on the 9th blink, I don't get the Red LED blink.

I really think I'm missing something pretty basic, but I just don't know what it is. Any help would be greatly appreciated.

**Comment by Garzlok** [comment]
Kept plugging away. I got it figured out. Thanks !

**Comment by noahbaron** [comment]
Great! Let me know if anything else comes up. We now use a custom board
with an RGB led in place of single red and green. So you will only see the
LED flash for red and green combinations when using an actual MDBT42Q.
Also, I am using firmware 2v01 since it has lower power consumption than
the later versions I tried, though I have never tried 2v06.
